set(STRUCTS_ROOT_DIR        "${CMAKE_SOURCE_DIR}"                           CACHE INTERNAL "")
set(STRUCTS_INCLUDE_DIR     "${STRUCTS_ROOT_DIR}/include"                   CACHE INTERNAL "")
set(STRUCTS_SOURCE_DIR      "${STRUCTS_ROOT_DIR}/src"                       CACHE INTERNAL "")
set(STRUCTS_PROJECT_DIR     "${STRUCTS_ROOT_DIR}/project"                   CACHE INTERNAL "")
set(STRUCTS_BIN_DIR         "${STRUCTS_ROOT_DIR}/bin"                       CACHE INTERNAL "")
set(STRUCTS_BIN_CONFIG_DIR  "${STRUCTS_BIN_DIR}/${STRUCTS_CONFIG_STRING}"   CACHE INTERNAL "")


set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${STRUCTS_BIN_CONFIG_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${STRUCTS_BIN_CONFIG_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${STRUCTS_BIN_CONFIG_DIR}")
